- name: demo on facts
  hosts: all
  tasks:
    - name: printing  URL
      ansible.builtin.debug:
        msg: OS Distro is {{ansible_distribution}}  


    - name: printing  Mac address
      ansible.builtin.debug:
        msg: ansible Mac address is {{macaddress}}        