- name: demo on facts
  hosts: all
  tasks:
    - name: printing  URL
      ansible.builtin.debug:
        msg: OS Distro is {{ansible_distribution}}  


    - name: printing  Mac Address
      ansible.builtin.debug:
        msg: ansible Mac Address is {{ansible_default_ipv4.macaddress}}  

    - name: printing Python version
      ansible.builtin.debug:
        msg: ansible Python version is {{ansible_python_version}}          