- name: Installing Nginx
  ansible.builtin.package:
    name: nginx 
    state: present 


#- name: Downloading frontend 
 #  src: https://github.com/stans-robot-project/frontend/archive/main.zip 
  #  dest: /tmp 
   # remote_src: yes   

- name: Download and Extract {{COMPONENT}}
  ansible.builtin.include_role:
    name: common 
    tasks_from: Download and extract     

- name: Cleanup of old html content 
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent   

- name: Coping frotend context to nginx path 
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html
    remote_src: yes   

- name: Coping proxy config 
  ansible.builtin.copy:
    src: roboshop.conf 
    dest: /etc/nginx/default.d/roboshop.conf  

- name: Starting Nginx Service 
  ansible.builtin.service:
    name: nginx 
    state: restarted
    enabled: yes      