- name: Coping {{COMPONENT}} repo file 
  ansible.builtin.copy:
    src: mysql.repo 
    dest: /etc/yum.repos.d/mongodb.repo  

- name: Installing {{COMPONENT}}
  ansible.builtin.yum:
    name:  
       - mysql-community-server 
       -  MySQL-python
    state: present  

- name: Starting {{COMPONENT}} Service 
  ansible.builtin.service:
    name:  mysqld
    state: started
    enabled: yes   


- name: Check the {{COMPONENT}} password by fetching from the logs 
  community.mysql.mysql_info:
    login_user: root
    login_password: RoboShop@1
  ignore_errors: yes         
  register: mysql_stat 

 # This will only be executed only if the above is a failure
- name: Fetching  Password
  ansible.builtin.shell: grep "temporary" /var/log/mysqld.log | head -n 1 | awk -F " " '{print $NF}'
  register: DEFAULT_ROOT_PASSWORD
  when: mysql_stat.failed   

- name: Copy the SQL Password Command file 
  ansible.buitin.copy: 
    src: root-password.sql 
    dest: /tmp/root-password.sql
  when: mysql_stat.failed   

- name: Changing  Password
  ansible.builtin.shell: mysql --connect-expired-password  -uroot -p"{{DEFAULT_ROOT_PASSWORD.stdout}}" < /tmp/root-password.sql 
  register: DEFAULT_ROOT_PASSWORD
  when: mysql_stat.failed     